### ISSUE TITLE
Lack of LTTngCds implementation?

### ISSUE THREAD

**Issue by ami-GS** [microsoft/Microsoft-Performance-Tools-Linux-Android#104]
Hi Team,

I'm writing MsQuic LTTng trace extension for WPA.
https://github.com/microsoft/msquic/pull/3294

I noticed lack of information in LTTngEvent which is actually in trace file.
As in image, vpid and vtid are stored in LTTngEvent.StreamDefinedEventContext as “_vpid” and “_vtid”.
However there is no cpu_id information which is stored in as stream.packet.context
Is this lack of LTTngCds implementation?

One of trace
[quic.babel.txt](https://github.com/microsoft/Microsoft-Performance-Tools-Linux-Android/files/10250510/quic.babel.txt)
The trace file exactly has cpu_id in stream.packet.context
![image](https://user-images.githubusercontent.com/5763034/208217773-aa4ee41f-4d19-4ee8-bfff-cb9ac6f17fba.png)
The cpu_id is not stored in LTTngEvent
![image](https://user-images.githubusercontent.com/5763034/208217777-9e100f42-9f30-480e-a409-67bae05c9aaa.png)

**Comment by ivberg** [comment]
Indeed, it looks like we don’t directly process [cpu_id from stream packet context](https://diamon.org/ctf/#ex-packet-context). I am not sure the original reason for that decision but maybe perf so we don't need to read it every time.

However, we do provide the CPU Id information based on reading the cpu from the channel name format – e.g. (channel0_11 is CPU 11). They should be equivalent.

This is available in LTTngContext CurrentCpu. I will add a unit test showing how this is exposed
