### ISSUE TITLE
WPA sometimes fails to load perf data

### ISSUE THREAD

**Issue by ami-GS** [microsoft/Microsoft-Performance-Tools-Linux-Android#107]
Hi team,

WPA sometimes fails to load perf artifact. sometimes work.

Here is my data and diagnostic console log
[handshake_f1000a.perf.data.txt](https://github.com/microsoft/Microsoft-Performance-Tools-Linux-Android/files/10523969/handshake_f1000a.perf.data.txt)
[Diagnostic_Console.txt](https://github.com/microsoft/Microsoft-Performance-Tools-Linux-Android/files/10523970/Diagnostic_Console.txt)

**Comment by ivberg** [comment]
Can you see if this issue reproduces with [Perfview ](https://github.com/microsoft/perfview) ?

We use the [TraceEvent ](https://github.com/microsoft/perfview/blob/6b4771eecba5ed00555a34d70e19a8742af4ee0a/documentation/TraceEvent/TraceEventLibrary.md) library to parse the perf files. Therefore any issue discovered in perf file parsing would need to be filed in that GitHub project.

The error in the diag console in "Microsoft.Diagnostics.Tracing.StackSources.LinuxPerfScriptProcessNameBuilder.SaveProcessName" is from that project

**Comment by ivberg** [comment]
Please let us know when the TraceEvent lib has a fix we can take

**Comment by ivberg** [comment]
Closing 3rd party issue
