### ISSUE TITLE
perf artifact recorded without -a option failed to be loaded

### ISSUE THREAD

**Issue by ami-GS** [microsoft/Microsoft-Performance-Tools-Linux-Android#108]
Not sure here is a right place.

perf artifact generated without -a option failed to be loaded. the one can be loaded with -a option

step
```sh
perf record -F 5000 -g -o out.perf.data ${COMMAND}
perf script -i out.perf.data > out.perf.data.txt
```

here is the data and diagnostic console log
[handshake_f5000.perf.data.txt](https://github.com/microsoft/Microsoft-Performance-Tools-Linux-Android/files/10523975/handshake_f5000.perf.data.txt)
[Diagnostic_Console.txt](https://github.com/microsoft/Microsoft-Performance-Tools-Linux-Android/files/10523974/Diagnostic_Console.txt)

**Comment by ivberg** [comment]
Can you see if this issue reproduces with [Perfview ](https://github.com/microsoft/perfview) ?

We use the [TraceEvent ](https://github.com/microsoft/perfview/blob/6b4771eecba5ed00555a34d70e19a8742af4ee0a/documentation/TraceEvent/TraceEventLibrary.md) library to parse the perf files. Therefore any issue discovered in perf file parsing would need to be filed in that GitHub project.
