### ISSUE TITLE
WPA cannot find this plugin even SET WPA_ADDITIONAL_SEARCH_DIRECTORIES

### ISSUE THREAD

**Issue by KotomiHacker** [microsoft/Microsoft-Performance-Tools-Linux-Android#113]
Environment: 

- Window 11
- `C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x64\3.1.32`
- WPA Version 10.6.20.1

Result
```
C:\Users\GAME>SET WPA_ADDITIONAL_SEARCH_DIRECTORIES=C:\tools\Microsoft-Performance-Tools-Linux-Android\MicrosoftPerfToolkitAddins
C:\Users\GAME>wpa.exe -listplugins

C:\Users\GAME>
                             - AVAILABLE PLUGINS -

        * XPerf

    For help, use -help <plugin name>
    For version information, use -version <plugin name>
```

**Comment by ivberg** [comment]
Where are you getting WPA from?

more the readme try the store version and try the launcher script. The script uses -addsearchdir and not the environment variable

Windows Only GUI - Install) Using the WPA GUI to load these tools as plugins

Download the latest Store [Windows Performance Analyzer (Preview)](https://www.microsoft.com/en-us/p/windows-performance-analyzer-preview/9n58qrw40dfw)

**Comment by KotomiHacker** [comment]
Thanks for the correct, it works with the store version!
I used to install it from ADK page.
