### ISSUE TITLE
LaunchWpaPerfToolsLinuxAndroid.bat does not work with latest Windows Performance Analyzer (Preview)

### ISSUE THREAD

**Issue by jppenttila** [microsoft/Microsoft-Performance-Tools-Linux-Android#121]
Windows Performance Analyzer (Preview) has been automatically updated in the end of last month and Microsoft-Performance-Tools-Linux-Android-1.5.5 release seems not to be compatible with it:
![image](https://github.com/microsoft/Microsoft-Performance-Tools-Linux-Android/assets/107250779/f3f9e6a8-4150-4023-9d17-9bf1515428b8)

![image](https://github.com/microsoft/Microsoft-Performance-Tools-Linux-Android/assets/107250779/9f82200d-7958-4e18-9c66-0dbf2fc19d8b)

**Comment by ivberg** [comment]
Thanks @jppenttila for reporting! Using your steps I was able to reproduce the same issue. 

I have reported the issue to the WPA team and will let you know what the status is once they triage the issue

**Comment by ivberg** [comment]
This should be fixed / worked around by #123 but I will not close until fully tested and a release is available

**Comment by ivberg** [comment]
Closed - should be fixed in 1.6.1

**Comment by jppenttila** [comment]
Verified that version 1.6.1 works, thank you!
