### ISSUE TITLE
Linux "perf" traces should allow multiple file names, not just "perf.data.txt"

### ISSUE THREAD

**Issue by dmachaj** [microsoft/Microsoft-Performance-Tools-Linux-Android#75]
It is my understanding that the file name contains important information about which type of trace is contained in the .txt file.  Fair enough.  However, I think it would be nice to change this `Equals` call to an `EndsWith` so that I can have different traces in the same directory with useful names, so long as they end with `.data.txt` or some equivalent.

https://github.com/microsoft/Microsoft-Performance-Tools-Linux-Android/blob/12065f920d5f81a41e61b4820db858820ef86dcf/PerfDataExtensions/SourceDataCookers/PerfDataProcessingSource.cs#L64

Alternatively, an arbitrary file extension could be used for this even if the data in the file is actually just .txt.

**Comment by dmachaj** [comment]
This is related to #74 but it is distinct.  Fixing 74 would provide guidance that the file name matters.  This issue would allow multiple files to be valid.

**Comment by ivberg** [comment]
Sounds reasonable to make this more flexible. Unfortunately, perf data decoded to a text format has no standard file extension, so we have to pick something here.
