### ISSUE TITLE
[Feature request] Perfetto - Display browser tab title alongside renderer view

### ISSUE THREAD

**Issue by linsword13** [microsoft/Microsoft-Performance-Tools-Linux-Android#90]
Thanks for this great tooling!

Feature request: It would be useful to display the corresponding browser tab title of a renderer. The Perfetto UI has that displayed and I find it a useful information for identifying interested processes/threads.

![image](https://user-images.githubusercontent.com/9145959/164777941-23bed965-9ab8-4c13-be66-83afc52e419d.png)

**Comment by ivberg** [comment]
Available in 1.5
