### ISSUE TITLE
"Open Unified" button not showing

### ISSUE THREAD

**Issue by xiaokaka-cpu** [microsoft/Microsoft-Performance-Tools-Linux-Android#96]
I have been using it for data analysis recently, but have encountered doubts. There is no "Open Unified" option after the plugin is loaded successfully. Can you help me find out why, thanks a lot.
![image](https://user-images.githubusercontent.com/106953397/172117413-bc7957e2-d96f-45d8-9c4b-df3a97c2a28d.png)
![image](https://user-images.githubusercontent.com/106953397/172117961-0514293a-96cb-4991-9450-5a746c45d28d.png)
I need something like this picture below
![image](https://user-images.githubusercontent.com/106953397/172120560-de7c8fe1-e90b-437d-9a14-91fd85b445b5.png)

**Comment by ivberg** [comment]
Thanks for reporting @xiaokaka-cpu. I verified the same as you with the latest [Windows Performance Analyzer (Preview)](https://apps.microsoft.com/store/detail/windows-performance-analyzer-preview/9N58QRW40DFW?hl=en-us&gl=US)

I have alerted the WPA team about this missing feature. FYI the "Open Unified" has now been renamed to "Single session"

**Comment by ivberg** [comment]
So the WPA team will look at updating the WPA Store (Preview) version to have this. Hopefully late next week. Meanwhile, as a workaround if you need it earlier, the ADK WPA version should hopefully support the "Single session" feature now. 
https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewADK

You will have to configure it manually to load the plugins per the readme. 

This old readme has instructions for using the ADK version.
https://github.com/microsoft/Microsoft-Performance-Tools-Linux-Android/commit/0b513bc184fd2f86239054bd0845fa4cd481b31e

**Comment by ivberg** [comment]
Closing as the "Single Session" feature is now available in [Windows Performance Analyzer (Preview)](https://apps.microsoft.com/store/detail/windows-performance-analyzer-preview/9N58QRW40DFW?hl=en-us&gl=US)
